### ISSUE TITLE
Performance on homogeneous graphs

### ISSUE THREAD

**Issue by xgfs** [Synerise/cleora#20]
Hi! I was trying to measure the performance of the Cleora on the homogeneous graphs used in the YouTube original paper, with no success. Specifically, I was trying to evaluate Blogcatalog, as it is the smallest graph.

I used the `./target/release/cleora -c "node node" ` configuration to get a single embedding per node. This way, the performance is close to random; however, on a different dataset with far simpler structure (CoCit dataset from the VERSE paper), I was able to obtain poor but not random performance - 0.21 Macro-F1 avg. for 5% labelled nodes, compared with ±30 for DW/VERSE.

Could you clarify if I am doing something horribly wrong, or the method needs some other hyperparameters to run properly? I would imagine adding a homogeneous example used across literature would strengthen the repository greatly. :)

**Comment by barbara3430** [comment]
Hi!
Here's a few ideas of what might have gone wrong:

1. In the mode you used: `-c node node` you will get 2 embeddings for some nodes - concretely, you will get a separate 'starting node embedding' and 'ending node embedding' if a node appears both as starting and ending node. For optimal performance, the embeddings should be concatenated.  If you set the parameter `-p --prepend-field-name`  to `1` you will be able to differentiate between the columns.

2. What is your iteration number `-n` and embedding dim `-d` ? We found ` -n 4 -d 1024` to be optimal in many settings.

3. You could take a look at our classification example in Python: https://github.com/Synerise/cleora/blob/master/example_classification.ipynb It uses the Facebook graph from SNAP, but the general idea is the same as in other homogeneous graphs. It will guide you through data preparation and embedding calculation (in a number of modes, i.e. "Star expansion" and "Clique expansion" which do not require embedding concatenation). It's possible that some modes of operation will work significantly better than others. 
This could also solve possible issues with input formatting or running Cleora.

4. We compared our classifcation results to LINE paper https://arxiv.org/pdf/1503.03578.pdf on the Youtube dataset and found comparable results, so I'm hopeful that it can be as good for BlogCatalog & VERSE :slightly_smiling_face: 
![Zrzut ekranu z 2021-01-07 12-30-28](https://user-images.githubusercontent.com/6282856/103891830-cc97c580-50ea-11eb-8b88-c0a0af549786.png)

**Comment by piobab** [comment]
Hi @xgfs! Did you have a chance to look at it? Any thoughts?

**Comment by piobab** [comment]
@xgfs we are going close the issue. If you find something just let us know but don't go too far :)
