### ISSUE TITLE
Calculation of embedding for new entity on-the-fly

### ISSUE THREAD

**Issue by nik3211** [Synerise/cleora#21]
As this module claims that Cleora embeddings of an entity are defined only by interactions with other entities, vectors for new entities can be computed on-the-fly.

Could you please help me with how to calculate embeddings for a new node? It will be really helpful if you can share a jupyter notebook on this as well.

**Comment by anonymous-kdd2021** [comment]
Hi! To compute embeddings for a new node it is enough to simply average the embeddings of its neighbors (using weighted averaging if edges have attached weights or some pairs of nodes are connected with more than 1 immediate edge). L2 normalization of the resulting embedding vector follows. Ideally the procedure should be done using embeddings from the preceding iteration (e.g. if you are using iteration number = 4, embeddings from iteration = 3 should be used for new node embedding construction), but it is not necessary and in most situations you can simply average using the current embeddings.

We have recently uploaded a paper with the algorithm description: https://arxiv.org/abs/2102.02302 which shows that the whole algorithm is comprised of weighted averaging of each node's neighbor embeddings. As such, node embedding computation by neighbor averaging simply repeats a single iteration of the algorithm.

**Comment by barbara3430** [comment]
Hi! To compute embeddings for a new node it is enough to simply average it's neigbor embeddings (using weighted averaging if edges have attached weights or pairs of nodes are connected with more than 1 immediate edge). L2 normalization of the new embedding vector follows. Ideally embeddings from the previous algorithm iteration should be used for this purpose (e.g. if you are using iteration number = 4, embeddings from iteration number = 3 should be used), but in most cases it works just as fine with your regular embeddings (in our example, this would be interation number = 4).

We have recently published a paper explaining the Cleora algorithm https://arxiv.org/pdf/2102.02302.pdf - this shows that Cleora is comprised of weighted averaging of each node's neighbor embeddings. So, with averaging a new node's neighbor embeddings you simply conduct another valid iteration of the algorithm.

**Comment by piobab** [comment]
@nik321 Have you handled it? If yes I will close the issue.

**Comment by nik3211** [comment]
Yeah, I have. Thanks :)
