### ISSUE TITLE
Usage with EMDE?

### ISSUE THREAD

**Issue by deklanw** [Synerise/cleora#23]
> Cleora is used by Synerise for internal purposes, working together with Terrarium DB processing billions of datapoints in real-time and solving multi-modal challenges which involves graph data. Cleora algorithm is flexible and can be applied to different segments of the market, inter alia: retail, banking, and telco behavioral data at scale (billions of entities, trillions of interactions). Cleora is also used in input embeddings in EMDE (Efficient Manifold Density Estimation) that was also created by the Synerise Team.

Is there an example of Cleora being used with EMDE somewhere?

The abstract of the EMDE paper says

> We release the source code and our own real-world dataset of e-commerce product purchases, with special focus on modeling of the item cold-start problem.

But the code doesn't appear to be public anywhere. I've been trying to replicate the method myself but I'd like to check a few details I'm not sure about

Thanks!

**Comment by piobab** [comment]
Hi @deklanw! 

Please take a look to the repo https://github.com/Synerise/booking-challenge. It can help you.

**Comment by deklanw** [comment]
Thanks that's very helpful.
