### ISSUE TITLE
To build cleora on Ubuntu 20.04 needs clang-11 

### ISSUE THREAD

**Issue by AlexMikhalev** [Synerise/cleora#24]
Hello all,
Great project, missing dependency in readme dependency on clang-11 (simd-json dependency) 
for ubuntu 20.04 I had to install from llvm repo:
```
export LLVM_VERSION=12
sudo add-apt-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main"
sudo apt-get install -y clang-$LLVM_VERSION lldb-$LLVM_VERSION lld-$LLVM_VERSION clangd-$LLVM_VERSION
```

**Comment by piobab** [comment]
@AlexMikhalev thanks! We will take a look and fix what is needed.

**Comment by piropaolo** [comment]
I did actually test it on a clean Ubuntu 20.04 installation, and no particular clang version was actually needed - although of course gcc and g++ were.
```
$ sudo apt install gcc
$ sudo apt install g++
```

for reference
```
$ rustc --version
rust 1.56.1 (59eed8a2a 2021-11-01)
$ cargo --version
cargo 1.56.0 (4ed5d137b 2021-10-04)
```

**Comment by piobab** [comment]
@AlexMikhalev I close the issue. Let us know if you have other problems.
