### ISSUE TITLE
Remove binaries from code repository and instead use Github Releases

### ISSUE THREAD

**Issue by kosciej** [Synerise/cleora#4]
Usually it's not a good practice to keep binaries in git source repository. It bloats repository size forever, which in turn causes a lot more data to be transferred when repository is cloned.  GitHub provides convenient solution for keeping and managing binary releases.

**Comment by piobab** [comment]
We are going to do it and other things around github pipelines as well.

**Comment by piobab** [comment]
@kosciej please take a look into https://github.com/Synerise/cleora/pull/6

**Comment by piobab** [comment]
https://github.com/Synerise/cleora/releases
