### ISSUE TITLE
Question about reproducing Dunhumby product complements/substitutes from white paper

### ISSUE THREAD

**Issue by tblazina** [Synerise/cleora#42]
Hello, 
Thanks for the cool project!

I was trying to reproduce the results of using Cleora to identify product complements/substitutes in the [Dunhumby Complete Journey](https://www.dunnhumby.com/source-files/#) shown in the [white paper](https://arxiv.org/pdf/2102.02302.pdf) but had a question about how the transaction data should be formatted and how the column types should be specified when running the Cleora binary:

I've formatted the transaction data by "basket" such that each row contains a user, and a sequence of product_ids
```
user_id <\t> product_id product_id product_id
user_id <\t> product_id product_id
user_id <\t> product_id product_id product_id product_id
```
and so on. and then I've run Cleora using...

for product complements:
`
./cleora-v1.1.1-x86_64-unknown-linux-gnu -i ./dunhumby_data/dh_clique.txt --columns="transient::user complex::products" -d 1024 -n 1 
`

and for product substitutes:
`
./cleora-v1.1.1-x86_64-unknown-linux-gnu -i ./dunhumby_data/dh_clique.txt --columns="transient::user complex::products" -d 1024 -n 4
`

After this just comparing cosine similarities and looking at the top 5 most similar "complements" and "substitutes" for one of the products form the white paper "SOUP RAMEN NOODLES/RAMEN CUPS 3 OZ", the complments and substitutes are not really similar to what is reported in the white paper. E.g. Top 3 Substitutes are 

```
BUTTER BUTTER 8OZ 
CODIMENTS/SAUCES BBQ SAUCE 18OZ
STATIONERY & SCHOOL SUPPLIES TAPE & MAILING PRODUCTS 60CT
```
instead of 

```
SOUP RAMEN NOODLES/RAMEN CUPS 3 OZ
SOUP RAMEN NOODLES/RAMEN CUPS 3 OZ
SOUP RAMEN NOODLES/RAMEN CUPS 3 OZ
```

As reported in the white paper.

I guess that I've not set the data up correctly or have specified the column types incorrectly. Is there code somewhere that describes using Cleora for this type of problem? Otherwise any hints would be greatly appreciated. Thanks!

**Comment by mkrzywda** [comment]
Hello @tblazina,

Could you told me more about your reproduce for Dunnhumby Complete Journey? Your differences from our results (in our white paper) exist only for complement and substitute for  "SOUP RAMEN NOODLES/RAMEN CUPS 3 OZ" or maybe for other products?

**Comment by tblazina** [comment]
Hi @mkrzywda, sure! No I have just used the  "SOUP RAMEN NOODLES/RAMEN CUPS 3 OZ" as one example, unfortunately none of the results look the same, which made me think either I was parsing the Dunhumby data incorrectly into a user transaction form, or that I've simply specified something wrong when running the model training.

the parsing of the Dunhumby data is done simply (following similar pattern from the [Link prediction colab notebook](https://cleora.readthedocs.io/en/latest/examples.html) which I realize is a different problem):

```python
import pandas as pd

def main():
    df = pd.read_csv('dunhumby_data/transaction_data.csv', sep=',')

    output_clique = "dunhumby_data/dh_clique.txt"
    output_star = "dunhumby_data/dh_star.txt"
    train = "dunhumby_data/dh_lp_train.txt"
    with open(output_clique, "w") as clique, open(output_star, "w") as star, open(train, "w") as f_train:
        grouped_basket = df.groupby(['household_key', 'BASKET_ID'])
        for n, (name, group) in enumerate(grouped_basket):
            group_list = group['PRODUCT_ID'].tolist()
            group_elems = list(map(str, group_list))
            clique.write("{}\t{}\n".format(name[0], ' '.join(group_elems)))
            star.write("{}\t{}\n".format(n, name[0]))
            for elem in group_elems:
                f_train.write("{}\t{}\n".format(name[0], elem))
                star.write("{}\t{}\n".format(n, elem))

if __name__ ==  "__main__":
    main()
```

and then to get the embeddings for complements/substitutes i've simply run (just changing the iteration parameter `-n`)

**Complements**:
```
./cleora-v1.1.1-x86_64-unknown-linux-gnu -i ./dunhumby_data/dh_clique.txt --columns="transient::user complex::products" -d 1024 -n 1
```

**Substitutes**:
```
./cleora-v1.1.1-x86_64-unknown-linux-gnu -i ./dunhumby_data/dh_clique.txt --columns="transient::user complex::products" -d 1024 -n 1
```

And then to just look qualitatively at the complements/substitutes similar to as done in the white paper (i.e. looked at cosine similarities in the embeddings) i've used the following snippet:

```python
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

prods = pd.read_csv('./dunhumby_data/products.csv')
embeddings = pd.read_csv('./emb__user__products.out', delimiter = " ", skiprows=[0], header=None, index_col=0)
ramen = prods[prods.SUB_COMMODITY_DESC == 'RAMEN NOODLES/RAMEN CUPS']

# Pick one of the RAMEN PRODUCT_IDS
example_embeddings = embeddings.loc[45720].values[1:]
cos_sims = []
for name,row in embeddings.iloc[1:].iterrows():
    cos_sims.append(cosine_similarity(example_embeddings[None, :], row.iloc[1:].values[None, :])[0][0])
cos_sims = np.array(cos_sims)
top_k = 5
top_items= embeddings.iloc[cos_sims.argsort()[-top_k:][::-1]].index
print(prods[prods.PRODUCT_ID.isin(top_items)])
```

I've tried a bunch of the different "RAMEN NOODLES/RAMEN CUPS 3 OZ" `PRODUCT_IDS`, and they give quite different results, none of which really match what is in the white paper. I observe the similar behavior with complementary products (i.e. n=1 iterations), and as i've said, it is similar for other examples from the white paper such as "BREAD BREAD:ITALIAN/FRENCH". 

Any idea where I might have gone wrong in trying to reproduce the results would be greatly appreciated. I'm very interested to look at complements/substitutes with similar transaction data I am working with but would like to first make sure I can reproduce what is in the white paper.

Thanks!

**Comment by mkrzywda** [comment]
@tblazina,

I prepared [notebook](https://colab.research.google.com/drive/1U8qnoigshIwDJT-A0LFUDs8FjZi-ZmwM#scrollTo=zFKU_YdTRdhG) for you with reproduction our White Paper. Feel free download or create copy from my notebook.For better performance you can skip cells with connect with google drive and run in your ML trainning enviroment examples with GPUs.

In a few days we will try to complete the documentation and add sample notebooks for dunnhumby and others uses cases in which we using Cleora.

Our preparing input data isn't this same what you can find in examples link prediction notebook. Also this same for `--columns `params. We using `complex::reflexive::CliqueNode` instead of `transient::user complex::products`.

**Comment by tblazina** [comment]
This is great @mkrzywda, thanks so much for taking the time to do that. I'll have a look through the notebook in detail and let you know if anything is unclear and I look forward to the other sample notebooks. Very much appreciated! 👍
