### ISSUE TITLE
/lib64/libc.so.6: version `GLIBC_2.18' not found

### ISSUE THREAD

**Issue by judas123** [Synerise/cleora#58]
I am trying to run Cleora on a simple dataset. My TSV file is simple and follows the format of "leads attributes"

l1 <\t> a1
l2 <\t> a1
l1<\t> a2
l3 <\t> a2

I am trying to run an embedding task with the following command from one of the jupyter notebook examples. I am trying to run it on a linux machine. 
```
#!/bin/bash
! ./new_method/cleora-v1.1.1-x86_64-unknown-linux-gnu --input DATA_PATH+'edges.tsv' --columns="leads attributes" --dimension 32 --number-of-iterations 4

```

I am getting the following error - 

```
./new_method/cleora-v1.1.1-x86_64-unknown-linux-gnu: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./new_method/cleora-v1.1.1-x86_64-unknown-linux-gnu)

```

Is there a solution to this ? Even with the latest version of the linux binary file, I get the same error.

**Comment by kodieg** [comment]
It seems that you have older glibc installed on your machine than cleora is linked to. Try too use musl version which should work regardless of your system version: https://github.com/Synerise/cleora/releases/download/v1.2.2/cleora-v1.2.2-x86_64-unknown-linux-musl

**Comment by judas123** [comment]
@kodieg , thanks that worked like a charm !
